name: Scheduled Execution
on:
  schedule:
    - cron: "0 0 * * *" # Runs scheduled daily at midnight UTC
  workflow_dispatch: # Allows manual execution for testing

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Enable debug mode for GitHub Actions
      - name: Enable Debug Mode
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      # Step 2: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12 # Replace with your Python version

      # Step 4: Decode Google credentials file (Base64-Decoded)
      - name: Decode Google credentials
        env:
          BASE64_GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_SREEHARI_CREDENTIALS }}
        run: |
          echo "Creating 'sheets' directory..."
          mkdir -p sheets  # Ensure sheets directory exists
          echo "Decoding Base64-encoded Google credentials..."
          echo "$BASE64_GOOGLE_CREDENTIALS" | base64 --decode | jq > sheets/sreehari-credentials.json
          echo "Google credentials decoded successfully and saved to sheets/sreehari-credentials.json"

      # Step 5: Install dependencies
      - name: Install Python dependencies
        run: |
          echo "Upgrading pip..."
          python -m pip install --upgrade pip
          echo "Installing Python dependencies from requirements.txt..."
          pip install -r requirements.txt
          echo "Installing additional dependencies..."
          pip install telethon langchain_openai pydantic python-dotenv gspread oauth2client

      # Step 6: Execute Python script
      - name: Execute Python script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
        run: |
          echo "Starting Python script execution..."
          python Azure.py
