name: Scheduled Execution

on:
  schedule:
    - cron: "0 0 * * *" # Runs scheduled daily at midnight UTC
  workflow_dispatch: # Allows manual execution for testing

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Debug Mode
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Decode Google credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_SHEET_SREEHARI_CREDENTIALS }}
        run: |
          mkdir -p sheets
          echo "$GOOGLE_CREDENTIALS_BASE64" | base64 -d > sheets/sreehari-credentials.json

      - name: Validate Google credentials file
        run: |
          echo "Validating decoded Google Sheets credentials file..."
          cat sheets/sreehari-credentials.json  # Output the file contents
        continue-on-error: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
        run: python Azure.py
