name: Run Telegram Job Posting Script

on:
  schedule:
    # Run daily at 6:35 PM UTC (12:05 AM IST)
    - cron: "35 18 * * *" # 6:35 PM UTC is 12:05 AM IST

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code in the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Create the cred.json file from GitHub's secret
      - name: Generate cred.json file
        uses: RizwanZahid/create-json@v1
        with:
          file-name: "cred.json"
          content: ${{ secrets.GCP_CRED_JSON }}

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Set up environment variables
      - name: Set up environment variables
        run: |
          echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> $GITHUB_ENV
          echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> $GITHUB_ENV
          echo "TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }}" >> $GITHUB_ENV
          echo "GOOGLE_SHEET_NAME=${{ secrets.GOOGLE_SHEET_NAME }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}" >> $GITHUB_ENV

      # Step 6: Run the script
      - name: Run the Python script
        run: python script.py
