name: Scheduled Execution

on:
  schedule:
    - cron: "0 0 * * *" # Runs scheduled daily at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12 # Replace with your required Python version

      # Step 3: Prepare and decode Google credentials file
      - name: Decode Google credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_SHEET_SREEHARI_CREDENTIALS }}
        run: |
          mkdir -p sheets
          echo "$GOOGLE_SHEET_SREEHARI_CREDENTIALS" | base64 -d > sheets/sreehari-credentials.json
          echo "Google credentials decoded and saved to sheets folder"

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install telethon langchain_openai pydantic python-dotenv gspread oauth2client

      # Step 5: Run the Python script
      - name: Execute Python script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
        run: python Azure.py
